const express = require('express');

const app = express();
const PORT = process.env.PORT || 3000;

const projects = [
  {
    name: 'Enterprise Fleet CMMS',
    summary: 'A multi-shop maintenance operations platform that connects work orders, inspections, parts, labor, accounting, and compliance in one role-scoped system for technicians, managers, and administrators.',
    image: '/img/malpais-mark.webp',
    visualLabel: 'Assets · Maintenance · Service',
    repoUrl: '',
    demoUrl: 'https://youtu.be/JcbvMJsJsL0',
    technologies: ['React', 'TypeScript', 'Supabase', 'PostgreSQL'],
    category: 'systems',
    year: '2026',
    featured: true,
    inProgress: true,
  },
  {
    name: 'Projection Show Engine',
    summary: 'A configuration-driven show engine for mapping native GPU-rendered media across surfaces, with timeline authoring, live calibration, and Raspberry Pi deployment.',
    image: '/img/projection-show-engine-project-v3.webp',
    repoUrl: 'https://github.com/AaronYangello/projection-mapper',
    demoUrl: 'https://youtu.be/IhSU3jyemdM',
    technologies: ['Python', 'FastAPI', 'ModernGL', 'React'],
    category: 'systems',
    year: '2026',
    featured: true,
    inProgress: true,
  },
  {
    name: 'YNot YNAB',
    summary: 'A Chrome extension that adds clearer planning, financial reports, retailer receipt capture, split transactions, and automated return matching to YNAB.',
    image: '/img/ynot-ynab-project-v2.webp',
    repoUrl: 'https://github.com/AaronYangello/ynot-ynab',
    demoUrl: '',
    technologies: ['TypeScript', 'React', 'Chrome MV3', 'YNAB API'],
    category: 'apps',
    year: '2026',
    featured: true,
    inProgress: false,
  },
  {
    name: 'Beacon',
    summary: 'A privacy-first iOS research prototype for finding trusted friends and family in crowded spaces through consent-aware location sharing and directional AR.',
    image: '/img/beacon-project.webp',
    repoUrl: '',
    demoUrl: '',
    technologies: ['React Native', 'Swift', 'ARKit', 'Supabase'],
    category: 'apps',
    year: '2026',
    featured: true,
    inProgress: true,
  },
  {
    name: 'AI Santa Phone',
    summary: 'A single-purpose phone that calls Santa, backed by speech recognition, natural-language processing, and a microservice architecture.',
    image: '/img/santa_phone_icon.png',
    repoUrl: 'https://github.com/AaronYangello/santa-phone',
    demoUrl: '',
    technologies: ['Python', 'Docker', 'SQL', 'AI/ML'],
    category: 'ai-data',
    year: '2024',
    featured: false,
    inProgress: true,
  },
  {
    name: 'BlackBerry Radar Adapter',
    summary: 'An integration adapter that connects fleet maintenance workflows with asset-location data and automates report processing.',
    image: '/img/blackberry_adapter_icon.jpeg',
    repoUrl: 'https://github.com/AaronYangello/BlackBerryRadarAdapter',
    demoUrl: '',
    technologies: ['Python', 'Systems Integration'],
    category: 'systems',
    year: '2024',
    featured: true,
    inProgress: false,
  },
  {
    name: 'Wordle Scoreboard',
    summary: 'A microservice-based app for tracking, comparing, and sharing Wordle scores with authentication, leaderboards, and real-time updates.',
    image: null,
    repoUrl: 'https://github.com/AaronYangello/wordle-scoreboard',
    demoUrl: '',
    technologies: ['Java', 'Docker', 'Next.js'],
    category: 'apps',
    year: '2025',
    featured: false,
    inProgress: true,
  },
  {
    name: 'Nextdoor Data Analysis',
    summary: 'A data pipeline that collects neighborhood posts, analyzes sentiment, and calculates resident satisfaction scores by town.',
    image: '/img/nextdoor_analyzer_icon.png',
    repoUrl: 'https://github.com/AaronYangello/next-door-analyzer',
    demoUrl: 'https://youtu.be/UkC2VhfTkeA',
    technologies: ['Python', 'Data Analysis'],
    category: 'ai-data',
    year: '2023',
    featured: false,
    inProgress: false,
  },
  {
    name: 'EEG Mind Reading Magician',
    summary: 'A brain-computer interface that processes EEG signals to identify a participant’s selected playing card in under five minutes.',
    image: '/img/eeg_magician_icon.png',
    repoUrl: '',
    demoUrl: 'https://youtu.be/t04jf4P-Rs8',
    technologies: ['MATLAB', 'Python', 'Signal Processing'],
    category: 'ai-data',
    year: '2016',
    featured: true,
    inProgress: false,
  },
  {
    name: 'Drone Delivery Simulator',
    summary: 'A simulation of autonomous grocery-delivery drones coordinating orders from a central hub to customer locations.',
    image: '/img/drone_delivery_simulator_icon.png',
    repoUrl: 'https://github.com/AaronYangello/drone-grocery-delivery-simulator',
    demoUrl: 'https://youtu.be/svghXJbNGos',
    technologies: ['Java', 'SQL', 'Docker'],
    category: 'systems',
    year: '2021',
    featured: false,
    inProgress: false,
  },
  {
    name: 'Actress Portfolio Site',
    summary: 'A responsive portfolio for headshots, reels, a résumé, and biography, with an intentionally lightweight content workflow.',
    image: null,
    repoUrl: 'https://github.com/AaronYangello/danayangelloNoCms',
    demoUrl: 'https://danayangello-no-cms.vercel.app/',
    technologies: ['Next.js', 'Tailwind CSS'],
    category: 'apps',
    year: '2025',
  },
  {
    name: 'Portfolio Website',
    summary: 'The site you are viewing: a focused, responsive showcase of selected software and experiments.',
    image: '/img/portfolio_icon.png',
    repoUrl: 'https://github.com/AaronYangello/portfolio-website',
    demoUrl: '',
    technologies: ['JavaScript', 'Node.js', 'CSS'],
    category: 'apps',
    year: '2024',
  },
  {
    name: 'Job Offer Comparison App',
    summary: 'A collaborative Android app that helps job seekers compare offers across compensation and quality-of-life factors.',
    image: '/img/job_comparison_icon.jpg',
    repoUrl: 'https://github.com/AaronYangello/job-offer-comparison-app',
    demoUrl: '',
    technologies: ['Java', 'Android'],
    category: 'apps',
    year: '2022',
  },
  {
    name: 'Household Appliance Survey',
    summary: 'A collaborative web application for collecting structured data about appliance types, brands, and household usage.',
    image: '/img/appliance_survey_icon.png',
    repoUrl: 'https://github.com/AaronYangello/household-appliance-survey',
    demoUrl: '',
    technologies: ['PHP', 'SQL', 'CSS'],
    category: 'apps',
    year: '2022',
  },
  {
    name: 'Yangello Wedding Website',
    summary: 'An event website that kept friends and family up to date and created a home for shared memories.',
    image: '/img/yangello_wedding_icon.png',
    repoUrl: 'https://github.com/AaronYangello/YangelloWedding',
    demoUrl: '',
    technologies: ['PHP', 'HTML', 'CSS'],
    category: 'apps',
    year: '2021',
  },
  {
    name: 'Skill Squatting Security Talk',
    summary: 'A concise presentation of research into skill-squatting attacks against voice assistants.',
    image: '/img/paper_presentation_icon.png',
    repoUrl: '',
    demoUrl: 'https://youtu.be/hjo9V2RZKzI',
    technologies: ['Security', 'Research'],
    category: 'systems',
    year: '2023',
  },
  {
    name: 'Embedded Battleship',
    summary: 'The classic strategy game rebuilt on an embedded system with low-level programming techniques.',
    image: '/img/embedded_battleship_icon.jpeg',
    repoUrl: 'https://github.com/AaronYangello/embedded-battleship',
    demoUrl: '',
    technologies: ['C/C++', 'Embedded'],
    category: 'embedded',
    year: '2018',
  },
  {
    name: 'Embedded Stick Runner',
    summary: 'A compact embedded-system take on the Chrome Dino Runner game, built around a simple jump mechanic.',
    image: '/img/stick_run_icon.png',
    repoUrl: 'https://github.com/AaronYangello/embedded-stick-runner',
    demoUrl: '',
    technologies: ['C/C++', 'Embedded'],
    category: 'embedded',
    year: '2018',
  },
  {
    name: 'Underwater Image Color Corrector',
    summary: 'MATLAB scripts that compensate for the loss of red and orange wavelengths in underwater photography.',
    image: '/img/underwater_image_color_corrector_icon.png',
    repoUrl: 'https://github.com/AaronYangello/underwater-image-color-corrector',
    demoUrl: '',
    technologies: ['MATLAB', 'Image Processing'],
    category: 'ai-data',
    year: '2018',
  },
  {
    name: 'Pet-Friendly Restaurant Simulator',
    summary: 'An interactive management simulation for a restaurant serving both people and their pets.',
    image: '/img/pet_friendly-restaurant-icon.png',
    repoUrl: 'https://github.com/AaronYangello/pet-friendly-restaurant-simulator',
    demoUrl: '',
    technologies: ['Java', 'Simulation'],
    category: 'apps',
    year: '2018',
  },
  {
    name: 'Coffee DB',
    summary: 'A desktop application for managing and querying a relational coffee database.',
    image: '/img/coffee_db_icon.png',
    repoUrl: 'https://github.com/AaronYangello/coffee-db',
    demoUrl: '',
    technologies: ['Java', 'SQL'],
    category: 'apps',
    year: '2017',
  },
  {
    name: 'Calendar App',
    summary: 'A lightweight desktop application for managing personal schedules.',
    image: '/img/calendar_app_icon.png',
    repoUrl: 'https://github.com/AaronYangello/calendar-app',
    demoUrl: '',
    technologies: ['Java'],
    category: 'apps',
    year: '2018',
  },
  {
    name: 'Text File Manipulation Tool',
    summary: 'A command-line utility that applies common transformations to text files.',
    image: '/img/tfmt_icon.png',
    repoUrl: 'https://github.com/AaronYangello/txt-manipulation-tool',
    demoUrl: '',
    technologies: ['Java', 'CLI'],
    category: 'systems',
    year: '2022',
  },
  {
    name: 'Kilometers to Miles Converter',
    summary: 'A focused JavaFX utility for converting distances from kilometers to miles.',
    image: '/img/km_to_mi_icon.png',
    repoUrl: 'https://github.com/AaronYangello/kilometer-to-miles-converter',
    demoUrl: '',
    technologies: ['Java', 'JavaFX'],
    category: 'apps',
    year: '2017',
  },
];

app.disable('x-powered-by');
app.set('view engine', 'ejs');
app.set('views', './views');
app.use(express.static('public'));

app.get('/', (req, res) => {
  res.render('index', { projects });
});

app.get('/resume', (req, res) => {
  res.redirect('/resume.pdf');
});

app.get('/github', (req, res) => {
  res.redirect('https://github.com/aaronyangello');
});

app.get('/linkedin', (req, res) => {
  res.redirect('https://linkedin.com/in/aaronyangello');
});

app.listen(PORT, () => {
  console.log(`Portfolio available at http://localhost:${PORT}`);
});
